spring:
  application:
    name: "smart-home-tech-collector"

kafka:
  properties:
    "bootstrap.servers": "localhost:9092"
    "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
    "value.serializer": "ru.yandex.practicum.telemetry.serialization.avro.serializer.SmartHomeTechAvroSerializer"
  topics:
    sensors: "telemetry.sensors.v1"
    hubs: "telemetry.hubs.v1"

grpc:
  server:
    port: 59091

logging:
  level:
    ru.practicum: DEBUG